name: IvalonaRoyaume
version: 2.0.0
main: fr.ivalona.royaume.IvalonaRoyaume
api-version: '26.2'
authors: [Ivalona]
softdepend: [Vault, PlaceholderAPI, Nexo, zMenu]
commands:
  ro:
    description: Commande principale des royaumes
    usage: /ro
    aliases: [royaume, kingdom]
permissions:
  ivalonaroyaume.admin:
    description: Administration complete d'IvalonaRoyaume
    default: op
  ivalonaroyaume.bypass:
    description: Ignore toutes les protections de claims
    default: op
